  name: Update stats

  on:
    schedule:
      # Runs at 12am UTC
      - cron: '0 0 * * *'
    workflow_dispatch:

  jobs:
    update-readme:
      name: Update Readme with Metrics
      runs-on: ubuntu-latest
      steps:
        - uses: athul/waka-readme@master
          with:
            WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
            SHOW_TITLE: true
    generate:
      runs-on: ubuntu-latest
      timeout-minutes: 10
      steps:
        # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
        - name: generate github-contribution-grid-snake.svg
          uses: Platane/snk/svg-only@v2
          with:
            github_user_name: ${{ github.repository_owner }}
            outputs: |
              assets/github-contribution-grid-snake.svg
              assets/github-contribution-grid-snake-dark.svg?palette=github-dark
