  name: Update stats

  on:
    schedule:
      # Runs at 12am UTC
      - cron: '0 0 * * *'
    workflow_dispatch:

  jobs:
    update-readme:
      name: Update Readme with Metrics
      runs-on: ubuntu-latest
      steps:
        - uses: athul/waka-readme@master
          with:
            WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
            SHOW_TITLE: true
    generate:
      runs-on: ubuntu-latest
      timeout-minutes: 10
      steps:
        # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
        - name: generate-snake-game-from-github-contribution-grid
          uses: Platane/snk@v2.2.1
          with:
            github_user_name: ${{ github.repository_owner }}
            outputs: |
              dist/github-contribution-grid-snake.svg
              dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        - name: push github-contribution-grid-snake.svg to the output branch
          uses: crazy-max/ghaction-github-pages@v3.1.0
          with:
            target_branch: output
            build_dir: dist
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
